language: python
sudo: required
python:
   - 3.6

before_install:
    - set -e  # fail on any error
    - sudo apt-get update -q

install:
   - pip install -r requirements.txt
   - pip install --editable .
   - pip install nose
script:
   - nosetests tests
